services:
  backend:
    build:
      context: ./backend
    container_name: t2d-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: t2d-frontend
    environment:
      - API_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
